name: BetterPrisons
author: snare
api: 5.3.0
version: 1.0.0
main: snare\BetterPrisons\BetterPrisons

depend:
  - BedrockEconomy

softdepend:
  - RankSystem
  - ScoreHud

permissions:
  betterprisons.rankup.command:
    default: true
  betterprisons.prestige.command:
    default: true
