database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: BetterPrisons.db
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

ranks:
  a:
    price: 1000
    added-permissions: []
    removed-permissions: []
    commands:
      - give {PLAYER} diamond 1
  b:
    price: 2500
    added-permissions: []
    removed-permissions: []
    commands: []
  c:
    price: 5000
    added-permissions: []
    removed-permissions: []
    commands: []
  d:
    price: 10000
    added-permissions: []
    removed-permissions: []
    commands: []
  e:
    price: 20000
    added-permissions: []
    removed-permissions: []
    commands: []
  f:
    price: 50000
    added-permissions: []
    removed-permissions: []
    commands: []
  g:
    price: 100000
    added-permissions: []
    removed-permissions: []
    commands: []
  h:
    price: 175000
    added-permissions: []
    removed-permissions: []
    commands: []
  i:
    price: 300000
    added-permissions: []
    removed-permissions: []
    commands: []
  j:
    price: 450000
    added-permissions: []
    removed-permissions: []
    commands: []
  k:
    price: 650000
    added-permissions: []
    removed-permissions: []
    commands: []
  l:
    price: 900000
    added-permissions: []
    removed-permissions: []
    commands: []
  m:
    price: 1200000
    added-permissions: []
    removed-permissions: []
    commands: []
  n:
    price: 1550000
    added-permissions: []
    removed-permissions: []
    commands: []
  o:
    price: 1900000
    added-permissions: []
    removed-permissions: []
    commands: []
  p:
    price: 2500000
    added-permissions: []
    removed-permissions: []
    commands: []
  q:
    price: 3150000
    added-permissions: []
    removed-permissions: []
    commands: []
  r:
    price: 3700000
    added-permissions: []
    removed-permissions: []
    commands: []
  s:
    price: 4400000
    added-permissions: []
    removed-permissions: []
    commands: []
  t:
    price: 5150000
    added-permissions: []
    removed-permissions: []
    commands: []
  u:
    price: 5900000
    added-permissions: []
    removed-permissions: []
    commands: []
  v:
    price: 6900000
    added-permissions: []
    removed-permissions: []
    commands: []
  w:
    price: 7000000
    added-permissions: []
    removed-permissions: []
    commands: []
  x:
    price: 8200000
    added-permissions: []
    removed-permissions: []
    commands: []
  y:
    price: 9300000
    added-permissions: []
    removed-permissions: []
    commands: []

# Rankup prices multiplied by this amount and then multiplied by the prestige of the player.

prestige-multiplier: 1.25

# Name the world players are teleported to after prestiging, leave empty for default world.

world-name: ""

# Enable or disable checking if players can break in mines if they have the required rank, requires MineSystem to function.

mine-crossover: true

# Max prestige, you should not specify any information for this prestige in the section below.

max-prestige: 4

prestiges:
  0:
    price: 12500000
    blocks-requirement: 10
    added-permissions: []
    removed-permissions: []
    commands: []
  1:
    price: 15000000
    blocks-requirement: 10000
    added-permissions: []
    removed-permissions: []
    commands: []
  2:
    price: 25000000
    blocks-requirement: 12500
    added-permissions: []
    removed-permissions: []
    commands: []
  3:
    price: 50000000
    blocks-requirement: 20000
    added-permissions: []
    removed-permissions: []
    commands: []

# Messages
max-rank: "&cYou are at the final rank, prestige using /prestige."
insufficient-rankup: "&cYou require ${PRICE} to rank up!"
ranked-up: "&aSuccessfully ranked up to &e{RANK} &afor &e${PRICE}&a!"
not-correct-rank: "&cYou are not at the required rank to mine here."
max-prestige-msg: "&cYou are at the maximum prestige!"
insufficient-prestige: "&cYou require ${PRICE} to prestige!"
must-be-z: "&cYou must be rank Z in order to prestige!"
prestiged: "&aYou have prestiged to prestige &e{PRESTIGE} &afor &e${PRICE}&a!"
not-enough-blocks: "&cYou have mined &e{CURRENT}/{REQUIRED} &cnumber of blocks that are required to prestige."